// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

/**
 * Plain stylesheets are imported for their side effects only (Bun's bundler
 * inlines them). Declared so `tsc --noEmit` accepts `import "./index.css"`.
 */
declare module "*.css";
